version: "3.9"
services:
  #Laravel Service
  laravel_app:
    container_name: laravel_app
    restart: always
    tty: true
    working_dir: /var/www/app
    build:
      args:
        user: laravel
        uid: 1000
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/app
    depends_on:
      - laravel_database
    links:
      - laravel_database
    networks:
      - laravel_network

  #DB Service
  laravel_database:
    image: mariadb:latest
    container_name: laravel_database
    restart: always
    working_dir: /etc/mysql
    tty: true
    environment:
      MYSQL_DATABASE: laravel_react
      MYSQL_USER: moeen
      MYSQL_ROOT_PASSWORD: basra
      MYSQL_PASSWORD: basra
    ports:
      - 3306:3306
    volumes:
      - ./.docker/db/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - laravel_network

  #Nginx Service
  laravel_server:
    image: nginx:alpine
    container_name: laravel_server
    restart: always
    tty: true
    ports:
      - 8100:8080
    volumes:
      - .:/var/www/app
      - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    depends_on:
      - laravel_app
    networks:
      - laravel_network

#Docker Networks
networks:
  laravel_network:
    driver: bridge
volumes:
  dbdata:
    driver: local
